package kze.backup.glacier;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class EntryPoint {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new EntryPoint().getGreeting());
    }
}
